include: package:flutter_lints/flutter.yaml
formatter:  
  page_width: 120

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
  
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 50
    maintainability-index: 40
    number-of-methods: 10
    weight-of-class: 0.33
    technical-debt:
      threshold: 1
      todo-cost: 161
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 414
      deprecated-annotations-cost: 37
      file-nullsafety-migration-cost: 41
      unit-type: "USD"

  exclude:
    rules:
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/*.config.dart"
      - "**/generated/**"
    metrics:
      - "**/*.g.dart"
      - "**/*.freezed.dart" 
      - "**/*.config.dart"
      - "**/generated/**"
      - "test/**"

analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_classes_with_only_static_members: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/generated/**'
    - 'test/**'

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - use_key_in_widget_constructors
    - always_use_package_imports
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - avoid_annotating_with_dynamic
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - invariant_booleans
    - no_leading_underscores_for_local_identifiers
    - prefer_asserts_in_initializer_lists
    - prefer_expression_function_bodies
    - throw_in_finally
    - unawaited_futures
    - avoid_unnecessary_containers
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - avoid_redundant_argument_values
    - sort_child_properties_last
    - avoid_returning_null_for_future
    - curly_braces_in_flow_control_structures
    - prefer_is_empty
    - library_prefixes
    - avoid_shadowing_type_parameters
    - cancel_subscriptions
    - control_flow_in_finally
    - file_names
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - prefer_mixin
    - secure_pubspec_urls
    - avoid_null_checks_in_equality_operators
    - empty_constructor_bodies
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - void_checks
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_init_to_null
    - await_only_futures
    - collection_methods_unrelated_type
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_this
    - unnecessary_string_escapes
    
    
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - implementation_imports
    - package_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - sort_unnamed_constructors_first
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
    
    
    - always_declare_return_types
    

    - annotate_overrides
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks    
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - eol_at_end_of_file
    - exhaustive_cases
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_asserts_with_message
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - provide_deprecation_message
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - test_types_in_equals
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unnecessary_constructor_name
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_string_interpolations
    - unreachable_from_main
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
