name: Manual Build & Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub Release'
        required: true
        default: 'true'

permissions:
  contents: write

env:
  FLUTTER_VERSION: stable
  PROJECT_PATH: arb_translator

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from pubspec
        id: version
        run: |
          VER=$(grep '^version:' ${{ env.PROJECT_PATH }}/pubspec.yaml | cut -d ' ' -f2)
          echo "version=$VER" >> $GITHUB_OUTPUT

  build:
    runs-on: ${{ matrix.os }}
    needs: version
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter (cached)
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Enable targets
        run: |
          if [ "${{ matrix.target }}" = "linux" ]; then flutter config --enable-linux-desktop; fi
          if [ "${{ matrix.target }}" = "windows" ]; then flutter config --enable-windows-desktop; fi
        shell: bash
      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev clang cmake ninja-build pkg-config liblzma-dev libsecret-1-dev
      - name: Pub get
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter pub get
      - name: Generate code
        working-directory: ${{ env.PROJECT_PATH }}
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build Linux
        if: matrix.target == 'linux'
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter build linux --release
      - name: Build Windows
        if: matrix.target == 'windows'
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter build windows --release
      - name: Package Linux artifact
        if: matrix.target == 'linux'
        run: tar -czf arb_translator-linux.tar.gz -C ${{ env.PROJECT_PATH }}/build/linux/x64/release/bundle .
      - name: Package Windows artifact
        if: matrix.target == 'windows'
        run: Compress-Archive -Path '${{ env.PROJECT_PATH }}\build\windows\x64\runner\Release\*' -DestinationPath arb_translator-windows.zip
      - name: Upload Linux artifact
        if: matrix.target == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: arb_translator-${{ matrix.target }}
          path: arb_translator-linux.tar.gz
          if-no-files-found: error
      - name: Upload Windows artifact
        if: matrix.target == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: arb_translator-${{ matrix.target }}
          path: arb_translator-windows.zip
          if-no-files-found: error

  release:
    needs: [build, version]
    if: ${{ github.event.inputs.create_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create tag
        run: |
          git fetch --tags
          if git rev-parse "v${{ needs.version.outputs.version }}" >/dev/null 2>&1; then
            echo 'Tag exists'; exit 0; fi
          git tag v${{ needs.version.outputs.version }}
          git push origin v${{ needs.version.outputs.version }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.version }}
          name: arb_translator v${{ needs.version.outputs.version }}
          body: Manual release
          files: |
            artifacts/arb_translator-linux/arb_translator-linux.tar.gz
            artifacts/arb_translator-windows/arb_translator-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
