name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  FLUTTER_VERSION: stable
  PROJECT_PATH: arb_translator
  LOCALES_DIR: arb_translator/lib/l10n

jobs:
  format_analyze:
    name: Format & Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter (cached)
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Flutter pub get
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter pub get
      - name: Dart format check
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          dart format --output=none --set-exit-if-changed .
      - name: Analyze
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter analyze

  tests:
    name: Tests (unit & widget)
    needs: format_analyze
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter (cached)
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Enable desktop targets (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: flutter config --enable-linux-desktop
      - name: Enable desktop targets (Windows only)
        if: matrix.os == 'windows-latest'
        run: flutter config --enable-windows-desktop
      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev clang cmake ninja-build pkg-config liblzma-dev
      - name: Pub get
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter pub get
      - name: Generate code
        working-directory: ${{ env.PROJECT_PATH }}
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run tests
        working-directory: ${{ env.PROJECT_PATH }}
        run: flutter test --no-pub

